### ISSUE TITLE
Cần scroll to top khi chuyển page trên desktop!

### ISSUE THREAD

**Issue by ctien** [luubinhan/blog#2]
Như tiêu đề anh nhé, khi nào rãnh thì fix lại nha!
Mà tại sao anh lại chuyển code sang vue vậy, gatsby bị làm sao mà anh bảo mệt mõi với nó, không phải nó đơn giản lại tốt cho SEO sao ạ ? Cần 1 video hoặc bài viết giải thích vụ này ạ. Thanks anh!

**Comment by luubinhan** [comment]
ok, thanks em, a đã chỉnh, khi nào rảnh anh viết giải thích
