### ISSUE TITLE
New gridsome-plugin-recommender version available

### ISSUE THREAD

**Issue by mklueh** [luubinhan/blog#3]
Hi,

I've seen you are using my plugin https://www.npmjs.com/package/gridsome-plugin-recommender , thank you :)

There is a new version that allows multiple new use cases that might be relevant for you, such as

1. Automatically tagging or categorizing your blog posts
1. Context-related ads on your pages
1. Other specific use cases that rely on multiple collections

You can read more about it here https://overflowed.dev/blog/building-a-gridsome-plugin-for-related-posts/

Best,

Marian

**Comment by luubinhan** [comment]
updated, thanks for awsome plugin
